### PR TITLE
Update Flathub badge

### PR DESCRIPTION
**Pull request by bragefuglseth**
Updates the link to Flathub's new badge endpoint

### CODE REVIEW

**Comment by cvfosammmm** [comment]
Why is this better? Please keep the width and height attributes.

**Comment by bragefuglseth** [comment]
The badge image hosted at dl.flathub.org uses a slightly older design. Flathub has later on modernized its badge infrastructure to have a more modern design generated on the fly at a new API endpoint, and the old static image is just kept around for backwards compatibility.

Here's a comparison:

Skjermbilde fra 2024-10-25 08-32-11

**Comment by bragefuglseth** [comment]
The size currently set in the README is nonstandard, but I wouldn't say that's super important, so I added it back.

**Comment by cvfosammmm** [comment]
Thanks for clarifying.

**Pull request merged**
